services:
  client:
    image: zfogg/zfo.gg:latest
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        SOURCE_COMMIT: ${SOURCE_COMMIT:-unknown}
    ports:
      - "5176:80"
